name: tests-payments

on:
  pull_request

jobs:
  build:
    env:
      STRAPI_KEY: TEST124
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd payments && npm install && npm run test:ci
