name: tests-payments

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    environment: test
    env:
      STRAPI_KEY: ${{ secrets.STRAPI_KEY }}
    steps:
      - uses: actions/checkout@v2
      - run: cd payments && npm install && npm run test:ci
