name: tests-payments

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Assign env variables
        env:
          STRAPI_KEY: TEST124
      - uses: actions/checkout@v2
      - run: cd payments && npm install && npm run test:ci
